services:
  server:
    build:
      context: ../server
    environment:
      NODE_ENV: production
      PGUSER: lanle
      PGDATABASE: opensea12pilot
      PGPASSWORD: jIhDGqxntC
      PGHOST: 113.161.52.34
      PGPORT: 5432
      PORT: 10001
      API_KEY_FOR_CALLING: 4234hds4-ih3492-49kqnf-a29g8r323a
      
    ports:
      - 10001:10001
