services:
  server:
    build:
      context: ../server
    environment:
      NODE_ENV: production
      PGUSER: opensea_report
      PGDATABASE: opensea12pro
      PGPASSWORD: waFoQizYruJIHR9d
      PGHOST: 172.16.1.210
      PGPORT: 5432
      PORT: 10001
      API_KEY_FOR_CALLING: 4234hds4-ih3492-49kqnf-a29g8r323a
      EMPLOYEE_API_KEY: 42@j4hja-9194jka-942429ba-582ouqv1
      
    ports:
      - 10001:10001
